name: "Development"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  test:
    name: Test and lint
    uses: open-sauced/open-sauced/.github/workflows/development.yml@main
